// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(MangaContext))]
    partial class MangaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Data.Entites.BuyingHistory", b =>
                {
                    b.Property<Guid>("UserIdentifer")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterIdentifer")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserIdentifer", "ChapterIdentifer");

                    b.ToTable("buying_history", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Data.Entites.Publisher", b =>
                {
                    b.Property<Guid>("PublisherIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("PublisherIdentifier");

                    b.HasIndex("UserIdentifier")
                        .IsUnique();

                    b.ToTable("publisher", (string)null);

                    b.HasData(
                        new
                        {
                            PublisherIdentifier = new Guid("51b02aef-2b58-4433-adea-e73c37b9f224"),
                            Description = "admin kiêm người đăng",
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72")
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Category", b =>
                {
                    b.Property<Guid>("CategoryIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("CategoryIdentifier");

                    b.ToTable("category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryIdentifier = new Guid("414e65b4-1949-48ce-a764-26fb66e95550"),
                            Description = "Thể loại theo sau một tội ác (như giết người hoặc mất tích) từ thời điểm nó được thực hiện cho đến thời điểm nó được giải quyết",
                            Name = "Mystery"
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("1b9d5460-4c32-4703-b4bd-c52e5fb6e943"),
                            Description = "Thường đề cập đến một loại tiểu thuyết thuộc thể loại viễn tưởng tập trung chủ yếu vào mối quan hệ và tình yêu lãng mạn giữa hai người, và thường có một kết thúc lạc quan và thỏa mãn về mặt cảm xúc",
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("ad2149ef-ac21-4759-88d8-e586e850e299"),
                            Description = "Lấy bối cảnh là một giai đoạn lịch sử và cố gắng truyền đạt tinh thần, cách cư xử và điều kiện xã hội của một thời đại đã qua với các chi tiết hiện thực và sự trung thực (trong một số trường hợp chỉ là sự trung thực bề ngoài) với sự thật lịch sử",
                            Name = "Historical"
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("edc6e266-7b95-4723-a420-8e51a78d99bc"),
                            Description = "Phương thức cụ thể của tiểu thuyết được thể hiện trong biểu diễn: một vở kịch, opera, kịch câm, múa ba lê, v.v., được trình diễn trong rạp hát, hoặc trên đài phát thanh hoặc truyền hình",
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("72522ef6-6633-4519-872b-36bc0675e328"),
                            Description = "Một thể loại của tiểu thuyết suy đoán liên quan đến các yếu tố ma thuật, thường lấy bối cảnh trong một vũ trụ hư cấu và đôi khi lấy cảm hứng từ thần thoại và văn hóa dân gian",
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("ddebafec-b0a5-49c6-ac6c-261079080dce"),
                            Description = "Thể loại bao gồm những cuốn sách mà nhân vật chính thực hiện một cuộc hành trình sử thi, về mặt cá nhân hoặc địa lý",
                            Name = "Adventure"
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("322dbf35-54aa-416e-b121-42fc20b9d94b"),
                            Description = "Một thể loại biên tập truyện tranh Nhật Bản nhắm đến đối tượng là các cậu bé vị thành niên",
                            Name = "Shounen"
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Chapter", b =>
                {
                    b.Property<Guid>("ChapterIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("ChapterNumber")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ComicIdentifier")
                        .HasColumnType("uuid");

                    b.Property<int>("UnlockPrice")
                        .HasColumnType("integer");

                    b.HasKey("ChapterIdentifier");

                    b.HasIndex("ComicIdentifier");

                    b.ToTable("chapter", (string)null);

                    b.HasData(
                        new
                        {
                            ChapterIdentifier = new Guid("3f5a415f-caa3-426b-8926-a11a55dc49b0"),
                            ChapterNumber = 1.0,
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787"),
                            UnlockPrice = 0
                        },
                        new
                        {
                            ChapterIdentifier = new Guid("ef26e85e-4bd5-414f-9a2b-40bc43534523"),
                            ChapterNumber = 1.0,
                            ComicIdentifier = new Guid("b8d6abf3-b7e0-4a20-8647-f8f4f1ac04d3"),
                            UnlockPrice = 0
                        },
                        new
                        {
                            ChapterIdentifier = new Guid("94f15b6a-a89b-4546-82a4-98098bab83ff"),
                            ChapterNumber = 1.0,
                            ComicIdentifier = new Guid("aadadaf7-fc21-4559-a53c-f97eb1ba583f"),
                            UnlockPrice = 0
                        },
                        new
                        {
                            ChapterIdentifier = new Guid("ab9d0e26-4c6e-40a8-97e3-1d5d012b4d80"),
                            ChapterNumber = 1.0,
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f"),
                            UnlockPrice = 0
                        },
                        new
                        {
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ChapterNumber = 1.0,
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e"),
                            UnlockPrice = 0
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ChapterImage", b =>
                {
                    b.Property<Guid>("ImageIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChapterIdentifier")
                        .HasColumnType("uuid");

                    b.Property<short>("ImageNumber")
                        .HasColumnType("smallint");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("ImageIdentifier");

                    b.HasIndex("ChapterIdentifier");

                    b.ToTable("chapter_image", (string)null);

                    b.HasData(
                        new
                        {
                            ImageIdentifier = new Guid("ad981387-1e98-4036-8934-868c5e0880a9"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)0,
                            ImageURL = "0.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("9a4c2922-3a3b-4cc1-ba2e-d62317c8c0e0"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)1,
                            ImageURL = "1.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("48a81e89-dbad-4fb5-b992-66b0a575d781"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)2,
                            ImageURL = "2.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("31ae274b-4dfc-4deb-af28-46de52cb6feb"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)3,
                            ImageURL = "3.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("cb4b4f62-523f-4044-9d58-1ae3f12d430c"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)4,
                            ImageURL = "4.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("3aaaa9a7-4465-494a-a7bd-08157d913586"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)5,
                            ImageURL = "5.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("7fb2316f-4341-401d-b28a-40146f8a7a0b"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)6,
                            ImageURL = "6.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("d9c7b2a1-67e0-4daa-8ad0-b8560938e847"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)7,
                            ImageURL = "7.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("25a2ab91-5674-44aa-bbac-2ea3bceb71d4"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)8,
                            ImageURL = "8.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("785fb0ef-b383-4f44-98b5-bd6a555f0626"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)9,
                            ImageURL = "9.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("c2fa7cbe-138b-42e5-ad7b-c0afd43f43fd"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)10,
                            ImageURL = "10.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("cb117933-9ccc-4ad6-afcf-65da344ba69a"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)11,
                            ImageURL = "11.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("d119637e-bf32-4b23-81ff-a09c1d910b81"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)12,
                            ImageURL = "12.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("e992e5d9-67a8-4164-9273-ae229e648556"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)13,
                            ImageURL = "13.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("bf280315-0e15-4074-978e-c0014a946383"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)14,
                            ImageURL = "14.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("97ce8e61-ac01-4e85-9a12-67d94f5b7102"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)15,
                            ImageURL = "15.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("1d73b99e-f451-4b55-9b20-ea4d572bc3a0"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)16,
                            ImageURL = "16.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("4aca6f3a-2ccf-49de-af02-0b1776e793ee"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)17,
                            ImageURL = "17.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("f78ffa61-a567-479a-aa79-011dfa2fdc4e"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)18,
                            ImageURL = "18.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("a79456c1-8024-4128-9a31-db46f7eeef08"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)19,
                            ImageURL = "19.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("2cd639ce-c96f-4589-8014-0e6e7f9ff69f"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)20,
                            ImageURL = "20.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("1c9b47b7-27a5-46c4-a8d0-e7163f1c3e7f"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)21,
                            ImageURL = "21.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("2abfb23c-34fa-4a48-b442-a1b28201ff32"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)22,
                            ImageURL = "22.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("45c4dfd6-910c-49a4-bb1c-f499377c8c61"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)23,
                            ImageURL = "23.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("64e10a07-b7f7-4335-9ef9-a3c7a5b67d7c"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)24,
                            ImageURL = "24.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("0e66730c-50f5-4f72-b8cd-2f720ddf6d7e"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)25,
                            ImageURL = "25.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("71147712-b450-4e4b-8df1-ed5d50160bf9"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)26,
                            ImageURL = "26.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("853addd5-5496-490f-86bd-cc12ba04e2bd"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)27,
                            ImageURL = "27.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("97c8d20b-0f88-47a6-91cb-e76d0b357ad3"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)28,
                            ImageURL = "28.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("19954bda-0156-48f9-aee6-c8c258dafa58"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)29,
                            ImageURL = "29.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("ae3756ad-6b22-4645-90c6-a01b60b04d59"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)30,
                            ImageURL = "30.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("bc5a3dbb-6b9e-4c4c-a013-f66ad22077dc"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)31,
                            ImageURL = "31.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("eec8c785-84cf-4b8e-bcf2-128a4d9876da"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)32,
                            ImageURL = "32.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("87e12554-c4a1-4bb7-906f-71c16042aaf3"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)33,
                            ImageURL = "33.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("b8f10d3d-74fb-448e-87a6-c2a46514e0e8"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)34,
                            ImageURL = "34.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("f1a77aa3-ffc5-4e9f-adcd-757545657941"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)35,
                            ImageURL = "35.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("6788fa1f-f257-4582-842e-ad505f1c8e92"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)36,
                            ImageURL = "36.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("f85d2bd9-6d9c-4a92-85b1-11c3ad17c133"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)37,
                            ImageURL = "37.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("a11be2b5-3c5c-4adc-8642-d2dfda33813d"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)38,
                            ImageURL = "38.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("4e86fa98-7b46-44e7-92bc-dcc997c3574a"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)39,
                            ImageURL = "39.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("22a1a283-80c0-4dc2-a9da-0a71a13b5dc0"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)40,
                            ImageURL = "40.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("3d6be27d-6bcc-4e23-9fde-f785d000a72e"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)41,
                            ImageURL = "41.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("5b2c0a01-6bc0-4b9c-b66f-72c45c8bdcb7"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)42,
                            ImageURL = "42.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("0c17d220-7f8e-4b58-b15d-a3f9d37a70dd"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)43,
                            ImageURL = "43.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("47059dc1-e213-4dc9-a1f3-1e263f7f29f2"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)44,
                            ImageURL = "44.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("34c310fd-4fdc-4048-9b11-7b0a29d3b440"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)45,
                            ImageURL = "45.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("6819a0d1-31a5-4e13-aaab-57fa19edc770"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)46,
                            ImageURL = "46.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("9f58f9f7-40c0-46bc-8052-7cb0ffca9a2c"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)47,
                            ImageURL = "47.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("7bd54d5b-d802-4d60-91a8-82a9079b1876"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)48,
                            ImageURL = "48.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("72b0ea4d-8f47-4e40-8fbb-9a5d5e1c87d3"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)49,
                            ImageURL = "49.png"
                        },
                        new
                        {
                            ImageIdentifier = new Guid("d3c2b7fa-2f9f-4883-862d-a9556d24a35d"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            ImageNumber = (short)50,
                            ImageURL = "50.png"
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Comic", b =>
                {
                    b.Property<Guid>("ComicIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<double>("LatestChapter")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateOnly>("PublishDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PublisherIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("ComicIdentifier");

                    b.HasIndex("PublisherIdentifier");

                    b.ToTable("comic", (string)null);

                    b.HasData(
                        new
                        {
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787"),
                            Avatar = "Thanh_Gươm_Diệt_Quỷ.jpg",
                            Description = "Kimetsu no Yaiba – Tanjirou là con cả của gia đình vừa mất cha. Một ngày nọ, Tanjirou đến thăm thị trấn khác để bán than, khi đêm về cậu ở nghỉ tại nhà người khác thay vì về nhà vì lời đồn thổi về ác quỷ luôn rình mò gần núi vào buổi tối. Khi cậu về nhà vào ngày hôm sau, bị kịch đang đợi chờ cậu…",
                            LatestChapter = 205.59999999999999,
                            Name = "Thanh Gươm Diệt Quỷ",
                            PublishDate = new DateOnly(2016, 11, 2),
                            PublisherIdentifier = new Guid("51b02aef-2b58-4433-adea-e73c37b9f224")
                        },
                        new
                        {
                            ComicIdentifier = new Guid("aadadaf7-fc21-4559-a53c-f97eb1ba583f"),
                            Avatar = "Hội_Pháp_Sư_Nhiệm_Vụ_Trăm_Năm.jpg",
                            Description = "Tuyện tiếp nối chap 545 của Fairy Tail, khi nhóm Natsu đi làm nhiệm vụ trăm năm.",
                            LatestChapter = 132.0,
                            Name = "Hội Pháp Sư Nhiệm Vụ Trăm Năm",
                            PublishDate = new DateOnly(2018, 7, 25),
                            PublisherIdentifier = new Guid("51b02aef-2b58-4433-adea-e73c37b9f224")
                        },
                        new
                        {
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f"),
                            Avatar = "Onepunch_Man.jpg",
                            Description = "Onepunch-Man là một Manga thể loại siêu anh hùng với đặc trưng phồng tôm đấm phát chết luôn… Lol!!! Nhân vật chính trong Onepunch-man là Saitama, một con người mà nhìn đâu cũng thấy “tầm thường”, từ khuôn mặt vô hồn, cái đầu trọc lóc, cho tới thể hình long tong. Tuy nhiên, con người nhìn thì tầm thường này lại chuyên giải quyết những vấn đề hết sức bất thường. Anh thực chất chính là một siêu anh hùng luôn tìm kiếm cho mình một đối thủ mạnh. Vấn đề là, cứ mỗi lần bắt gặp một đối thủ tiềm năng, thì đối thủ nào cũng như đối thủ nào, chỉ ăn một đấm của anh là… chết luôn. Liệu rằng Onepunch-Man Saitaman có thể tìm được cho mình một kẻ ác dữ dằn đủ sức đấu với anh? Hãy theo bước Saitama trên con đường một đấm tìm đối cực kỳ hài hước của anh!!\r\n\r\n",
                            LatestChapter = 232.0,
                            Name = "Onepunch Man",
                            PublishDate = new DateOnly(2018, 3, 26),
                            PublisherIdentifier = new Guid("51b02aef-2b58-4433-adea-e73c37b9f224")
                        },
                        new
                        {
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e"),
                            Avatar = "Black_Clover_Thế_Giới_Phép_Thuật.jpg",
                            Description = "Aster và Yuno là hai đứa trẻ bị bỏ rơi ở nhà thờ và cùng nhau lớn lên tại đó. Khi còn nhỏ, chúng đã hứa với nhau xem ai sẽ trở thành Ma pháp vương tiếp theo. Thế nhưng, khi cả hai lớn lên, mọi sô chuyện đã thay đổi. Yuno là thiên tài ma pháp với sức mạnh tuyệt đỉnh trong khi Aster lại không thể sử dụng ma pháp và cố gắng bù đắp bằng thể lực. Khi cả hai được nhận sách phép vào tuổi 15, Yuno đã được ban cuốn sách phép cỏ bốn bá (trong khi đa số là cỏ ba lá) mà Aster lại không có cuốn nào. Tuy nhiên, khi Yuno bị đe dọa, sự thật về sức mạnh của Aster đã được giải mã- cậu ta được ban cuốn sách phép cỏ năm lá, cuốn sách phá ma thuật màu đen. Bấy giờ, hai người bạn trẻ đang hướng ra thế giới, cùng chung mục tiêu.",
                            LatestChapter = 360.0,
                            Name = "Black Clover - Thế Giới Phép Thuật",
                            PublishDate = new DateOnly(2015, 4, 18),
                            PublisherIdentifier = new Guid("51b02aef-2b58-4433-adea-e73c37b9f224")
                        },
                        new
                        {
                            ComicIdentifier = new Guid("b8d6abf3-b7e0-4a20-8647-f8f4f1ac04d3"),
                            Avatar = "Thần_Y_Đích_Nữ.jpg",
                            Description = "Một nữ quân y đặc cấp trong bộ đội lục chiến, thánh thủ trung tây y, tinh thông võ thuật, tiễn thuật vì một tai nạn trên không mà xuyên không về lịch sử. Mang trên mình mối thù, nàng sẽ làm gì đây?",
                            LatestChapter = 302.0,
                            Name = "Thần Y Đích Nữ",
                            PublishDate = new DateOnly(2016, 5, 26),
                            PublisherIdentifier = new Guid("51b02aef-2b58-4433-adea-e73c37b9f224")
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ComicCategory", b =>
                {
                    b.Property<Guid>("CategoryIdentifier")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComicIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryIdentifier", "ComicIdentifier");

                    b.HasIndex("ComicIdentifier");

                    b.ToTable("comic_category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryIdentifier = new Guid("edc6e266-7b95-4723-a420-8e51a78d99bc"),
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("72522ef6-6633-4519-872b-36bc0675e328"),
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("322dbf35-54aa-416e-b121-42fc20b9d94b"),
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("1b9d5460-4c32-4703-b4bd-c52e5fb6e943"),
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("ad2149ef-ac21-4759-88d8-e586e850e299"),
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("ddebafec-b0a5-49c6-ac6c-261079080dce"),
                            ComicIdentifier = new Guid("aadadaf7-fc21-4559-a53c-f97eb1ba583f")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("72522ef6-6633-4519-872b-36bc0675e328"),
                            ComicIdentifier = new Guid("aadadaf7-fc21-4559-a53c-f97eb1ba583f")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("ddebafec-b0a5-49c6-ac6c-261079080dce"),
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("322dbf35-54aa-416e-b121-42fc20b9d94b"),
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("edc6e266-7b95-4723-a420-8e51a78d99bc"),
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("72522ef6-6633-4519-872b-36bc0675e328"),
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("322dbf35-54aa-416e-b121-42fc20b9d94b"),
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("414e65b4-1949-48ce-a764-26fb66e95550"),
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("1b9d5460-4c32-4703-b4bd-c52e5fb6e943"),
                            ComicIdentifier = new Guid("b8d6abf3-b7e0-4a20-8647-f8f4f1ac04d3")
                        },
                        new
                        {
                            CategoryIdentifier = new Guid("414e65b4-1949-48ce-a764-26fb66e95550"),
                            ComicIdentifier = new Guid("b8d6abf3-b7e0-4a20-8647-f8f4f1ac04d3")
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ComicSaving", b =>
                {
                    b.Property<Guid>("ComicIdentifier")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavingTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ComicIdentifier", "UserIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("comic_saving", (string)null);

                    b.HasData(
                        new
                        {
                            ComicIdentifier = new Guid("b8d6abf3-b7e0-4a20-8647-f8f4f1ac04d3"),
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            SavingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5199)
                        },
                        new
                        {
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e"),
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            SavingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5202)
                        },
                        new
                        {
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f"),
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            SavingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5203)
                        },
                        new
                        {
                            ComicIdentifier = new Guid("4dfe12e0-cb8a-4282-8e74-3b1e8053f787"),
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            SavingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5205)
                        },
                        new
                        {
                            ComicIdentifier = new Guid("aadadaf7-fc21-4559-a53c-f97eb1ba583f"),
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            SavingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5206)
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ReadingHistory", b =>
                {
                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterIdentifier")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastReadingTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserIdentifier", "ChapterIdentifier");

                    b.HasIndex("ChapterIdentifier");

                    b.ToTable("reading_history", (string)null);

                    b.HasData(
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            ChapterIdentifier = new Guid("3f5a415f-caa3-426b-8926-a11a55dc49b0"),
                            LastReadingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5083)
                        },
                        new
                        {
                            UserIdentifier = new Guid("1ef67686-f4ad-48f2-b56c-c828ec53a8d5"),
                            ChapterIdentifier = new Guid("ef26e85e-4bd5-414f-9a2b-40bc43534523"),
                            LastReadingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5129)
                        },
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            ChapterIdentifier = new Guid("ef26e85e-4bd5-414f-9a2b-40bc43534523"),
                            LastReadingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5131)
                        },
                        new
                        {
                            UserIdentifier = new Guid("1ef67686-f4ad-48f2-b56c-c828ec53a8d5"),
                            ChapterIdentifier = new Guid("3f5a415f-caa3-426b-8926-a11a55dc49b0"),
                            LastReadingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5133)
                        },
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            LastReadingTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5134)
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ReviewChapter", b =>
                {
                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<short>("RatingStar")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ReviewTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserIdentifier", "ChapterIdentifier");

                    b.HasIndex("ChapterIdentifier");

                    b.ToTable("review_chapter", (string)null);

                    b.HasData(
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            ChapterIdentifier = new Guid("3f5a415f-caa3-426b-8926-a11a55dc49b0"),
                            Comment = "Nó hay vãi",
                            RatingStar = (short)5,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4999)
                        },
                        new
                        {
                            UserIdentifier = new Guid("1ef67686-f4ad-48f2-b56c-c828ec53a8d5"),
                            ChapterIdentifier = new Guid("3f5a415f-caa3-426b-8926-a11a55dc49b0"),
                            Comment = "Art đẹp, nhưng cốt truyện không hay",
                            RatingStar = (short)3,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5003)
                        },
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            ChapterIdentifier = new Guid("dc31637b-416c-458d-9942-74fa1470ca20"),
                            Comment = "Art tạm tạm",
                            RatingStar = (short)2,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5005)
                        },
                        new
                        {
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            ChapterIdentifier = new Guid("ab9d0e26-4c6e-40a8-97e3-1d5d012b4d80"),
                            Comment = "Meh không ổn tí nào",
                            RatingStar = (short)1,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5006)
                        },
                        new
                        {
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            ChapterIdentifier = new Guid("94f15b6a-a89b-4546-82a4-98098bab83ff"),
                            Comment = "Được phết",
                            RatingStar = (short)4,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(5008)
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ReviewComic", b =>
                {
                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComicIdentifier")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<short>("RatingStar")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ReviewTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserIdentifier", "ComicIdentifier");

                    b.HasIndex("ComicIdentifier");

                    b.ToTable("review_comic", (string)null);

                    b.HasData(
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e"),
                            Comment = "Tổng quan về cốt truyện ở mức ổn",
                            RatingStar = (short)3,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4920)
                        },
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f"),
                            Comment = "Cốt truyện khó hiểu",
                            RatingStar = (short)2,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4925)
                        },
                        new
                        {
                            UserIdentifier = new Guid("1ef67686-f4ad-48f2-b56c-c828ec53a8d5"),
                            ComicIdentifier = new Guid("5d34237a-f44c-4f3f-8495-2b36047e034e"),
                            Comment = "Cười vãi",
                            RatingStar = (short)5,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4927)
                        },
                        new
                        {
                            UserIdentifier = new Guid("1ef67686-f4ad-48f2-b56c-c828ec53a8d5"),
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f"),
                            Comment = "Tui muốn gud end",
                            RatingStar = (short)1,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4928)
                        },
                        new
                        {
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            ComicIdentifier = new Guid("8aa5080b-0212-4b9c-9b70-0afc2bc4b99f"),
                            Comment = "Đánh nhau ít nhưng tổng quan vẫn OK",
                            RatingStar = (short)4,
                            ReviewTime = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4930)
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.TransactionsHistory", b =>
                {
                    b.Property<Guid>("TransactionIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Amount")
                        .HasColumnType("NUMERIC(6, 0)");

                    b.Property<int>("Coin")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("transaction_history", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionIdentifier = new Guid("0e7687cc-491a-4e65-a4f1-1480aeb42675"),
                            Amount = 100000.0,
                            Coin = 100,
                            Date = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4851),
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72")
                        },
                        new
                        {
                            TransactionIdentifier = new Guid("7204b04a-9b40-4e79-824b-9a3536634ff4"),
                            Amount = 50000.0,
                            Coin = 50,
                            Date = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4856),
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72")
                        },
                        new
                        {
                            TransactionIdentifier = new Guid("dd97131a-c97b-4494-8767-98db0baeaaeb"),
                            Amount = 200000.0,
                            Coin = 200,
                            Date = new DateTime(2023, 6, 8, 8, 34, 53, 413, DateTimeKind.Utc).AddTicks(4858),
                            UserIdentifier = new Guid("1ef67686-f4ad-48f2-b56c-c828ec53a8d5")
                        });
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.UserInfo", b =>
                {
                    b.Property<Guid>("UserIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccountBalance")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("VARCHAR(13)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("UserIdentifier");

                    b.ToTable("user_access", (string)null);

                    b.HasData(
                        new
                        {
                            UserIdentifier = new Guid("2231dfa9-c0f7-49c9-b0af-dac2cac61c72"),
                            AccountBalance = 30,
                            Avatar = "User_Empty.png",
                            BirthDay = new DateOnly(2003, 12, 3),
                            Email = "ledinhdangkhoa10a9@gmail.com",
                            FullName = "Lê Đình Đăng Khoa",
                            Gender = 0,
                            Password = "Jackpie2003",
                            PhoneNumber = "0706042250",
                            UserName = "Jackpieking"
                        },
                        new
                        {
                            UserIdentifier = new Guid("1ef67686-f4ad-48f2-b56c-c828ec53a8d5"),
                            AccountBalance = 100,
                            Avatar = "User_Empty.png",
                            BirthDay = new DateOnly(2003, 4, 2),
                            Email = "nghialt123@gmail.com",
                            FullName = "Lee Trung Nghĩa",
                            Gender = 0,
                            Password = "NghiaLe123",
                            PhoneNumber = "0903591555",
                            UserName = "wibulord"
                        },
                        new
                        {
                            UserIdentifier = new Guid("c6d20823-3d00-48a0-8074-36587bee2693"),
                            AccountBalance = 0,
                            Avatar = "User_Empty.png",
                            BirthDay = new DateOnly(2003, 8, 15),
                            Email = "lamvd@gmail.com",
                            FullName = "Võ Đại Lâm",
                            Gender = 0,
                            Password = "Lam123",
                            PhoneNumber = "02343883333",
                            UserName = "lamvd"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Data.Entites.BuyingHistory", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Chapter", "Chapter")
                        .WithMany("BuyingHistories")
                        .HasForeignKey("UserIdentifer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementAPI.Data.Entites.UserInfo", "UserInfo")
                        .WithMany("BuyingHistories")
                        .HasForeignKey("UserIdentifer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("DataAccessLayer.Data.Entites.Publisher", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.UserInfo", "UserInfo")
                        .WithOne("Publisher")
                        .HasForeignKey("DataAccessLayer.Data.Entites.Publisher", "UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Chapter", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Comic", "Comic")
                        .WithMany("Chapters")
                        .HasForeignKey("ComicIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ChapterImage", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Chapter", "Chapter")
                        .WithMany("ChapterImages")
                        .HasForeignKey("ChapterIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Comic", b =>
                {
                    b.HasOne("DataAccessLayer.Data.Entites.Publisher", "Publisher")
                        .WithMany("Comics")
                        .HasForeignKey("PublisherIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ComicCategory", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Category", "Category")
                        .WithMany("ComicCategories")
                        .HasForeignKey("CategoryIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MangaManagementAPI.Data.Entites.Comic", "Comic")
                        .WithMany("ComicCategories")
                        .HasForeignKey("ComicIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ComicSaving", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Comic", "Comic")
                        .WithMany("ComicSavings")
                        .HasForeignKey("ComicIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementAPI.Data.Entites.UserInfo", "UserInfo")
                        .WithMany("ComicSavings")
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ReadingHistory", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Chapter", "Chapter")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("ChapterIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementAPI.Data.Entites.UserInfo", "UserInfo")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ReviewChapter", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Chapter", "Chapter")
                        .WithMany("ReviewChapters")
                        .HasForeignKey("ChapterIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementAPI.Data.Entites.UserInfo", "UserInfo")
                        .WithMany("ReviewChapters")
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.ReviewComic", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.Comic", "Comic")
                        .WithMany("ReviewComics")
                        .HasForeignKey("ComicIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementAPI.Data.Entites.UserInfo", "UserInfo")
                        .WithMany("ReviewComics")
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comic");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.TransactionsHistory", b =>
                {
                    b.HasOne("MangaManagementAPI.Data.Entites.UserInfo", "UserInfo")
                        .WithMany("TransactionHistories")
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("DataAccessLayer.Data.Entites.Publisher", b =>
                {
                    b.Navigation("Comics");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Category", b =>
                {
                    b.Navigation("ComicCategories");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Chapter", b =>
                {
                    b.Navigation("BuyingHistories");

                    b.Navigation("ChapterImages");

                    b.Navigation("ReadingHistories");

                    b.Navigation("ReviewChapters");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.Comic", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("ComicCategories");

                    b.Navigation("ComicSavings");

                    b.Navigation("ReviewComics");
                });

            modelBuilder.Entity("MangaManagementAPI.Data.Entites.UserInfo", b =>
                {
                    b.Navigation("BuyingHistories");

                    b.Navigation("ComicSavings");

                    b.Navigation("Publisher");

                    b.Navigation("ReadingHistories");

                    b.Navigation("ReviewChapters");

                    b.Navigation("ReviewComics");

                    b.Navigation("TransactionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
